DROP POLICY IF EXISTS user_flags_self ON user_flags;
DROP POLICY IF EXISTS user_progress_self ON user_progress;

ALTER TABLE user_flags NO FORCE ROW LEVEL SECURITY;
ALTER TABLE user_progress NO FORCE ROW LEVEL SECURITY;

ALTER TABLE user_flags DISABLE ROW LEVEL SECURITY;
ALTER TABLE user_progress DISABLE ROW LEVEL SECURITY;
