/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Account {
  accessToken: string | null;
  accessTokenExpiresAt: Timestamp | null;
  accountId: string;
  createdAt: Generated<Timestamp>;
  id: string;
  idToken: string | null;
  password: string | null;
  providerId: string;
  refreshToken: string | null;
  refreshTokenExpiresAt: Timestamp | null;
  scope: string | null;
  updatedAt: Generated<Timestamp>;
  userId: string;
}

export interface ChunkDrills {
  answer: string;
  chunk_id: string;
  id: string;
  pieces: string[] | null;
  prompt: string;
  sort_order: Generated<number>;
  type: string;
}

export interface ChunkExamples {
  chunk_id: string;
  english: string;
  id: string;
  japanese: string;
  sort_order: Generated<number>;
}

export interface Chunks {
  created_at: Generated<Timestamp>;
  id: string;
  is_active: Generated<boolean>;
  level: string | null;
  meaning_ja: string;
  nuance: string;
  phrase: string;
  situation: string;
  sort_order: Generated<number>;
  unit_id: string | null;
  updated_at: Generated<Timestamp>;
}

export interface Courses {
  created_at: Generated<Timestamp>;
  description: string | null;
  id: string;
  is_active: Generated<boolean>;
  sort_order: Generated<number>;
  title: string;
  updated_at: Generated<Timestamp>;
}

export interface CourseUnits {
  course_id: string;
  description: string | null;
  id: string;
  sort_order: Generated<number>;
  title: string;
}

export interface SchemaMigrations {
  dirty: boolean;
  version: Int8;
}

export interface Session {
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: string;
  ipAddress: string | null;
  token: string;
  updatedAt: Generated<Timestamp>;
  userAgent: string | null;
  userId: string;
}

export interface User {
  createdAt: Generated<Timestamp>;
  email: string;
  emailVerified: Generated<boolean>;
  id: string;
  image: string | null;
  name: string;
  updatedAt: Generated<Timestamp>;
}

export interface UserCourses {
  course_id: string;
  started_at: Generated<Timestamp>;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface UserDrillResults {
  chunk_id: string;
  created_at: Generated<Timestamp>;
  id: string;
  result: string;
  user_id: string;
}

export interface UserFlags {
  chunk_id: string;
  created_at: Generated<Timestamp>;
  flag: string;
  user_id: string;
}

export interface UserProgress {
  chunk_id: string;
  completed_count: Generated<number>;
  last_completed_at: Timestamp | null;
  last_seen_at: Timestamp | null;
  seen_count: Generated<number>;
  user_id: string;
}

export interface UserStreaks {
  current_streak: Generated<number>;
  last_practiced_on: Timestamp | null;
  longest_streak: Generated<number>;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface Verification {
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: string;
  identifier: string;
  updatedAt: Generated<Timestamp>;
  value: string;
}

export interface DB {
  account: Account;
  chunk_drills: ChunkDrills;
  chunk_examples: ChunkExamples;
  chunks: Chunks;
  course_units: CourseUnits;
  courses: Courses;
  schema_migrations: SchemaMigrations;
  session: Session;
  user: User;
  user_courses: UserCourses;
  user_drill_results: UserDrillResults;
  user_flags: UserFlags;
  user_progress: UserProgress;
  user_streaks: UserStreaks;
  verification: Verification;
}
